<?php 
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */
if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly
class umdc_postslides {
   private $post_slides_options;

   public function __construct() {
      add_action( 'admin_menu', array( $this, 'umdc_post_slides_add_plugin_page' ) );
      add_action( 'admin_init', array( $this, 'umdc_post_slides_page_init' ) );
   }

   public function umdc_post_slides_add_plugin_page() {
      add_options_page(
         'Ultimate Multi Design', // page_title
         'Ultimate Multi Design', // menu_title
         'manage_options', // capability
         'Ultimate Multi Design', // menu_slug
         array( $this, 'umdc_post_slides_create_admin_page' ) // function
      );
   }

   public function umdc_post_slides_create_admin_page() {
      $this->post_slides_options = get_option( 'umdc_setting_option' ); ?>

      <div class="wrap">
         <h2>Ultimate Multi Design</h2>         

         <form method="post" action="options.php">
            <?php
               settings_fields( 'umdc_post_slides_option_group' );
               do_settings_sections( 'umdc_post-slides-admin' );
               submit_button();
            ?>
         </form>
      </div>
   <?php }

   public function umdc_post_slides_page_init() {
      register_setting(
         'umdc_post_slides_option_group', // option_group
         'umdc_setting_option', // option_name
         array( $this, 'umdc_post_slides_sanitize' ) // sanitize_callback
      );

      add_settings_section(
         'umdc_post_slides_setting_section', // id
         'Settings', // title
         array( $this, 'umdc_post_slides_section_info' ), // callback
         'umdc_post-slides-admin' // page
      );

      add_settings_field(
         'umdc_pause', // id
         'Slide Speed', // title
         array( $this, 'umdc_pause_callback' ), // callback
         'umdc_post-slides-admin', // page
         'umdc_post_slides_setting_section' // section
      );

      add_settings_field(
         'umdc_auto_start', // id
         'Auto Start', // title
         array( $this, 'umdc_auto_start_callback' ), // callback
         'umdc_post-slides-admin', // page
         'umdc_post_slides_setting_section' // section
      );

      add_settings_field(
         'umdc_enable_loop', // id
         'Enable Loop', // title
         array( $this, 'umdc_enable_loop_callback' ), // callback
         'umdc_post-slides-admin', // page
         'umdc_post_slides_setting_section' // section
      );

      add_settings_field(
         'umdc_pause_on_hover', // id
         'Pause On Hover', // title
         array( $this, 'umdc_pause_on_hover_callback' ), // callback
         'umdc_post-slides-admin', // page
         'umdc_post_slides_setting_section' // section
      );

      add_settings_field(
         'umdc_enable_keypress', // id
         'Enable Keypress', // title
         array( $this, 'umdc_enable_keypress_callback' ), // callback
         'umdc_post-slides-admin', // page
         'umdc_post_slides_setting_section' // section
      );

      add_settings_field(
         'umdc_next_previous_controls', // id
         'Next-Previous Controls', // title
         array( $this, 'umdc_next_previous_controls_callback' ), // callback
         'umdc_post-slides-admin', // page
         'umdc_post_slides_setting_section' // section
      );

      add_settings_field(
         'umdc_enable_touch', // id
         'Enable Touch', // title
         array( $this, 'umdc_enable_touch_callback' ), // callback
         'umdc_post-slides-admin', // page
         'umdc_post_slides_setting_section' // section
      );

      add_settings_field(
         'umdc_enable_drag', // id
         'Enable Drag', // title
         array( $this, 'umdc_enable_drag_callback' ), // callback
         'umdc_post-slides-admin', // page
         'umdc_post_slides_setting_section' // section
      );
   }

   public function umdc_post_slides_sanitize($input) {
      $sanitary_values = array();

      if ( isset( $input['umdc_pause'] ) ) {
         $sanitary_values['umdc_pause'] = sanitize_text_field( $input['umdc_pause'] );
      }

      if ( isset( $input['umdc_auto_start'] ) ) {
         $sanitary_values['umdc_auto_start'] = $input['umdc_auto_start'];
      }

      if ( isset( $input['umdc_enable_loop'] ) ) {
         $sanitary_values['umdc_enable_loop'] = $input['umdc_enable_loop'];
      }

      if ( isset( $input['umdc_pause_on_hover'] ) ) {
         $sanitary_values['umdc_pause_on_hover'] = $input['umdc_pause_on_hover'];
      }

      if ( isset( $input['umdc_enable_keypress'] ) ) {
         $sanitary_values['umdc_enable_keypress'] = $input['umdc_enable_keypress'];
      }

      if ( isset( $input['umdc_next_previous_controls'] ) ) {
         $sanitary_values['umdc_next_previous_controls'] = $input['umdc_next_previous_controls'];
      }

      if ( isset( $input['umdc_enable_touch'] ) ) {
         $sanitary_values['umdc_enable_touch'] = $input['umdc_enable_touch'];
      }

      if ( isset( $input['umdc_enable_drag'] ) ) {
         $sanitary_values['umdc_enable_drag'] = $input['umdc_enable_drag'];
      }

      return $sanitary_values;
   }

   public function umdc_post_slides_section_info() {
      
   }

    public function umdc_pause_callback() {
      printf(
         '<input class="regular-text" type="text" name="umdc_setting_option[umdc_pause]" id="pause" value="%s">',
         isset( $this->post_slides_options['umdc_pause'] ) ? esc_attr( $this->post_slides_options['umdc_pause']) : ''
      );
   }
   

   public function umdc_auto_start_callback() {
      ?> <fieldset><?php $checked = ( isset( $this->post_slides_options['umdc_auto_start'] ) && $this->post_slides_options['umdc_auto_start'] === 'true' ) ? 'checked' : '' ; ?>
      <label for="auto_start-0"><input type="radio" name="umdc_setting_option[umdc_auto_start]" id="auto_start-0" value="true" <?php echo $checked; ?>> True</label><br>
      <?php $checked = ( isset( $this->post_slides_options['umdc_auto_start'] ) && $this->post_slides_options['umdc_auto_start'] === 'false' ) ? 'checked' : '' ; ?>
      <label for="auto_start-1"><input type="radio" name="umdc_setting_option[umdc_auto_start]" id="auto_start-1" value="false" <?php echo $checked; ?>> False</label></fieldset> <?php
   }

   public function umdc_enable_loop_callback() {
      ?> <fieldset><?php $checked = ( isset( $this->post_slides_options['umdc_enable_loop'] ) && $this->post_slides_options['umdc_enable_loop'] === 'true' ) ? 'checked' : '' ; ?>
      <label for="enable_loop-0"><input type="radio" name="umdc_setting_option[umdc_enable_loop]" id="enable_loop-0" value="true" <?php echo $checked; ?>> True</label><br>
      <?php $checked = ( isset( $this->post_slides_options['umdc_enable_loop'] ) && $this->post_slides_options['umdc_enable_loop'] === 'false' ) ? 'checked' : '' ; ?>
      <label for="enable_loop-1"><input type="radio" name="umdc_setting_option[umdc_enable_loop]" id="enable_loop-1" value="false" <?php echo $checked; ?>> False</label></fieldset> <?php
   }

   public function umdc_pause_on_hover_callback() {
      ?> <fieldset><?php $checked = ( isset( $this->post_slides_options['umdc_pause_on_hover'] ) && $this->post_slides_options['umdc_pause_on_hover'] === 'true' ) ? 'checked' : '' ; ?>
      <label for="pause_on_hover-0"><input type="radio" name="umdc_setting_option[umdc_pause_on_hover]" id="pause_on_hover-0" value="true" <?php echo $checked; ?>> True</label><br>
      <?php $checked = ( isset( $this->post_slides_options['umdc_pause_on_hover'] ) && $this->post_slides_options['umdc_pause_on_hover'] === 'false' ) ? 'checked' : '' ; ?>
      <label for="pause_on_hover-1"><input type="radio" name="umdc_setting_option[umdc_pause_on_hover]" id="pause_on_hover-1" value="false" <?php echo $checked; ?>> False</label></fieldset> <?php
   }

   public function umdc_enable_keypress_callback() {
      ?> <fieldset><?php $checked = ( isset( $this->post_slides_options['umdc_enable_keypress'] ) && $this->post_slides_options['umdc_enable_keypress'] === 'true' ) ? 'checked' : '' ; ?>
      <label for="enable_keypress-0"><input type="radio" name="umdc_setting_option[umdc_enable_keypress]" id="enable_keypress-0" value="true" <?php echo $checked; ?>> True</label><br>
      <?php $checked = ( isset( $this->post_slides_options['umdc_enable_keypress'] ) && $this->post_slides_options['umdc_enable_keypress'] === 'false' ) ? 'checked' : '' ; ?>
      <label for="enable_keypress-1"><input type="radio" name="umdc_setting_option[umdc_enable_keypress]" id="enable_keypress-1" value="false" <?php echo $checked; ?>> False</label></fieldset> <?php
   }

   public function umdc_next_previous_controls_callback() {
      ?> <fieldset><?php $checked = ( isset( $this->post_slides_options['umdc_next_previous_controls'] ) && $this->post_slides_options['umdc_next_previous_controls'] === 'true' ) ? 'checked' : '' ; ?>
      <label for="next_previous_controls-0"><input type="radio" name="umdc_setting_option[umdc_next_previous_controls]" id="next_previous_controls-0" value="true" <?php echo $checked; ?>> True</label><br>
      <?php $checked = ( isset( $this->post_slides_options['umdc_next_previous_controls'] ) && $this->post_slides_options['umdc_next_previous_controls'] === 'false' ) ? 'checked' : '' ; ?>
      <label for="next_previous_controls-1"><input type="radio" name="umdc_setting_option[umdc_next_previous_controls]" id="next_previous_controls-1" value="false" <?php echo $checked; ?>> False</label></fieldset> <?php
   }

   public function umdc_enable_touch_callback() {
      ?> <fieldset><?php $checked = ( isset( $this->post_slides_options['umdc_enable_touch'] ) && $this->post_slides_options['umdc_enable_touch'] === 'true' ) ? 'checked' : '' ; ?>
      <label for="enable_touch-0"><input type="radio" name="umdc_setting_option[umdc_enable_touch]" id="enable_touch-0" value="true" <?php echo $checked; ?>> True</label><br>
      <?php $checked = ( isset( $this->post_slides_options['umdc_enable_touch'] ) && $this->post_slides_options['umdc_enable_touch'] === 'false' ) ? 'checked' : '' ; ?>
      <label for="enable_touch-1"><input type="radio" name="umdc_setting_option[umdc_enable_touch]" id="enable_touch-1" value="false" <?php echo $checked; ?>> False</label></fieldset> <?php
   }

   public function umdc_enable_drag_callback() {
      ?> <fieldset><?php $checked = ( isset( $this->post_slides_options['umdc_enable_drag'] ) && $this->post_slides_options['umdc_enable_drag'] === 'true' ) ? 'checked' : '' ; ?>
      <label for="enable_drag-0"><input type="radio" name="umdc_setting_option[umdc_enable_drag]" id="enable_drag-0" value="true" <?php echo $checked; ?>> True</label><br>
      <?php $checked = ( isset( $this->post_slides_options['umdc_enable_drag'] ) && $this->post_slides_options['umdc_enable_drag'] === 'false' ) ? 'checked' : '' ; ?>
      <label for="enable_drag-1"><input type="radio" name="umdc_setting_option[umdc_enable_drag]" id="enable_drag-1" value="false" <?php echo $checked; ?>> False</label></fieldset> <?php
   }

}
if ( is_admin() )
   $post_slides = new umdc_postslides();
?>